### ISSUE TITLE
업체 요구사항 TO-DO

### ISSUE THREAD

**Issue by BlindedShooter** [BlindedShooter/ICP-Prototype#6]
# 요구사항
- [ ] 핀터레스트식 메인 화면
- [ ] ~이미지 검색~
- [ ] 방송 녹화, 이전 방송 리스트 접근
- [ ] 방송은 동시에 하지 않음.
- [ ] 본사: 상품 등록, 매니저 알림
- [ ] 매니저: 상품 선택, 고객 선택 + 초대, 방송
- [ ] 고객: 초대 승인 (고객 승인 여부 확인 가능, 재생 시간?), 방송 시청, 장바구니 + 구매 + 결제
- [ ] 모드 선택: 채팅, 방송, 상품 상세

# 프론트엔드
## 메인 화면
- [ ] 검색창 구현
- [ ] 하단 메인 액션 바 (홈 + 알림)
### 초기 화면
- [ ] 상단 매니저 (tv) 목록
- [ ] 상품 목록 + 라이브가 있다면 첫번째로 노출
### 매니저 선택 시
- [ ] 녹화본 썸네일 자동 슬라이드 형식
- [ ] 홍보했던 상품 목록(? 취급 상품 목록?)
## 방송화면 (고객 측)
- [ ] 영상 스트리밍
- [ ] 판매자와 채팅 -> 채팅창 확대?
- [ ] 장바구니 담기
- [ ] 간단한 매니저 정보 -> 매니저 정보
### 상품 상세
- [ ] 홍보 상품 목록
- [ ] 상품 상세 화면
### 방송 설정
- [ ] 상품 선택
- [ ] 고객 선택
- [ ] 알림 여부 선택
- [ ] 방송 제목
### 방송 진행
- [ ] 영상 확인
- [ ] 구매자와 채팅
- [ ] 현재 상품 선택

## 알림
- [ ] 알림 뷰
- [ ] 알림 리스트

# 백엔드
- [ ] 회원 (매니저, 고객) 정보 DB
- [ ] 상품 DB
- [ ] 세션 로그 ("매니저, 상품", 참여자, 채팅 로그, 녹화본 링크)

## 상품 관리
